spes: Add missing vendor.xiaomi.hardware.mtdservice@1.3 target
error: vendor/xiaomi/spes/Android.bp:6734:1: "libmt@1.3" depends on undefined module "vendor.xiaomi.hardware.mtdservice@1.3".
Or did you mean ["vendor.xiaomi.hardware.mtdservice@1.0" "vendor.xiaomi.hardware.mtdservice@1.1" "vendor.xiaomi.hardware.mtdservice@1.2"]?